@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

JsonSerializableFitBizStorage "1" *-right-> "*" JsonAdaptedClient
JsonAdaptedClient "1" *-right-> "*" JsonAdaptedExercise

@enduml
