@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Client "1" *--> "1" UniqueExerciseList
UniqueExerciseList "1" *--> "*" Exercise

Exercise "1" *--> "1" ExerciseName
Exercise "1" *--> "1" ExerciseReps
Exercise "1" *--> "1" ExerciseSets
Exercise "1" *--> "1" ExerciseDate
Exercise "1" *--> "1" ExerciseWeight
@enduml
