@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Client *-down-> "1" PersonalBest

PersonalBestFinder -left-> PersonalBest : sets >
PersonalBestFinder -left-> "1" Client
PersonalBestFinder -down-> "1" UniqueExerciseList

ViewCommand -down-> "1" PersonalBestFinder
AddExerciseCommand -down-> "1" PersonalBestFinder
DeleteExerciseCommand -left-> "1" PersonalBestFinder

@enduml
