= FitBiz - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/AY1920S2-CS2103T-F11-2/main

By: `CS2103T-F11-2` Since: `Feb 2020` Licence: `MIT`

== Introduction

FitBiz is a business management tool tailor made for fitness coaches to manage their clients. From managing your client's profile to planning your schedules, FitBiz will surely ease the pain and monotony of managing a small to medium client portfolio.

This program is primarily a desktop application and optimised for those who prefer to work with a Command Line Interface (CLI). If you can type fast, and have clients to train and manage, FitBiz is definitely for you!

== Quick Start

. Ensure you have Java 11 or above installed in your Computer
. Download the latest `FitBiz.jar` link:{repoURL}/releases[here]
. Copy the file to the folder you want to use as the home folder for your Fitness Manager
. Double-click the file to start the app. The GUI should appear in a few seconds
. Type the command in the command box and press Enter to execute it. e.g. typing help and pressing Enter will open the help window.
. Some example commands you can try:
* `list` : lists all clients
* `add-c n/John Doe g/Male p/98765432 e/johnd@example.com a/John street, block 123, #01-01 b/24-12-1997 h/170 cw/70 tw/75`
: adds a client named John Doe to FitBiz
* `exit` : exits the app
. Refer to <<Features>> below for details of each command

== Features
s
*Format of Commands*

* Words in `UPPER_SNAKE_CASE` are the parameters to be supplied by the user
e.g. in `add-c n/NAME`, `NAME` is a parameter which can be used as `add-c n/John Doe`
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`
* Items with `…` after them can be used multiple times including zero times e.g. `[t/TAG]…` can be used as (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable

=== View help: `help`

Lists all available commands and a short description of what they do. Specify the command for more detailed explanation.

Format: `help [c/COMMAND]`

Examples:

* `help`
** Lists all commands
* `help add-c`
** Shows a detailed explanation of the `add-c` command

=== Add a new client profile: `add-c`

Initialises and adds a new client profile.

Format: `add-c n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [g/GENDER] [h/HEIGHT] [cw/CURRENT_WEIGHT] [tw/TARGET_WEIGHT] [r/REMARK] [s/SPORT]… [t/TAG]…`

* `n/NAME` is case insensitive. e.g `hans` will match `Hans`
* The order of words will matter. e.g `Hans Ong` will not match `Ong Hans`
* Only exact match will be shown. e.g. `Hans` will not match `Hans Ong`
* A client can have any number of tags (including 0)

Examples:

* `add-c n/Ming Liang p/98765432 e/johnd@example.com a/John street, block 123, #01-01`
** Adds a new client: Ming Liang with the above information
* `add-c n/Low Tah Kiow, John t/powerlifter e/betsycrowe@example.com a/some street p/1234567 t/strongman`
** Adds a new client: Low Tah Kiow, John with the above information

=== View a client profile: `view-c`

Shows all available information of the client at the specified index.

Format: `view-c INDEX`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)

Examples:

* `view-c 3`
** Shows information about the 3rd client
* `view-c 45`
** Shows information about the 45th client

=== Edit a client’s profile: `edit-c`

Edits the client’s cliental details by specifying the attribute and the new value.

Format: `edit-c INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [g/GENDER] [h/HEIGHT] [cw/CURRENT_WEIGHT] [tw/TARGET_WEIGHT] [r/REMARK] [s/SPORT]… [t/TAG]...`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)
* At least one of the optional fields must be provided
* When editing tags, the existing tags of the client will be removed i.e adding of tags is not cumulative
* You can remove all the client’s tags by typing `t/`` without specifying any tags after it

Examples:

* `edit-c 1 n/Ming Liang a/age v/60 a/gender v/male`
** Edits the name of the 1st client to Ming Liang, age to 60, and gender to male.

=== Delete a client: `delete-c`

Deletes the client at the specified index from the program.

Format: `delete-c INDEX`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)

Examples:

* `delete-c 4`
** Deletes the 4th client from the program

=== List all clients: `list-c`

Shows all clients currently entered in this program.

* Note that this is the default view when you first launch FitBiz

Format: `list-c`

=== Record a client's exercise: `add-e`

Adds and records an exercise to a client at the specified index.

Format: `add-e CLIENT_INDEX e/EXERCISE_NAME [d/DATE] [w/WEIGHT] [r/REMARKS]`

* `CLIENT_INDEX` refers to the index number shown in the displayed client list
* `CLIENT_INDEX` must be a positive integer (ie. 1, 2, 3, ...)
* If `DATE` is not specified, it will be defaulted to the current day
* `DATE` must be of the form `DD-MM-YYYY` (ie. 02-07-2020 for 2nd July 2020)

Examples:

* `add-e 2 e/Push Ups d/25-02-2020 r/50 Reps`
** Adds an exercise called "Push Ups" with remarks "50 reps" on 2nd July 2020 to the 2nd client
* `add-e 3 e/Bench Press d/26-02-2020 w/120 r/10 Reps`
** Adds an exercise called "Bench Press" of weight 120kg with remarks "50 reps" on 2nd July 2020 to the 3rd client

=== Start a timer: `time`

Starts a timer which will notify you when it ends.

Format: `time [h/HOURS] [m/MINUTES] [s/SECONDS]`

Examples:

* `time m/4 s/40`
** Starts a timer for 4 minutes and 40 seconds

=== Filter clients based on attribute: `filter-c`

Filters the client list by the specified keyword(s) that matches the name or any attributes the client has.

Format: `filter-c KEYWORD [MORE_KEYWORDS]`

* The search is case insensitive. e.g `push ups` will match `Push Ups`
* The order of the keywords does not matter (e.g. `Push Pull` will match `Pull Push`)
* Only full words will be matched e.g. `Push` will not match `Push Pull`
* Clients matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber, Bo Yang`

Examples:

* `filter-c Johnny`
** Returns a client list of `Johnny Tim` and `johnny`

=== View cliental best: `view-pb`

Displays the cliental best of all exercises of the client at the specified index.

Format: `view-pb INDEX`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)

Example:

* `view-pb 6`
** Shows the cliental best for all exercises done by the 6th client

=== View schedule for the day/week: `view-s`

Shows the schedule for today or the time specified.

Format: `view-s TYPE`

* `TYPE` must be either `today`, `week` or `month`

Examples:

* `view schedule today`
** Shows the schedule for today
* `view schedule week`
** Shows the schedule of the current week

=== Export as CSV: `export`

Exports a client’s training record to a CSV file.

Format: `export INDEX`

* `INDEX` refers to the index number shown in the displayed client list
* `INDEX` must be a positive integer (ie. 1, 2, 3, ...)

Example:

* `export 6`
** Exports training records of the 6th client

=== Display visualisations of training progress: `graph`

Shows visualisations of a client’s exercise progress.

Format: `graph e/EXERCISE_NAME [s/START] [e/END]`

* Generates a graphical representation of the client’s progress
* If `START` or `END` is not specified, it will default to the current month
* Date format of `[s/START]`, `[e/END]` is `DD-MM-YYYY`
* This command can only be used while viewing a client (ie. right after `view-c` is used)

Examples:

* `graph e/Push Ups`
** Shows a graph of Ming Liang’s Push Ups progress over the current month

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous FitBiz folder.
